title: first-coding-course
description: first coding course using git
template:
  repo: first-coding-course-template
  name: first-coding-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
